run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - gofmt
    - revive
    - ineffassign
    - typecheck

linters-settings:
  gofmt:
    simplify: true
  revive:
    ignore-generated-header: true

issues:
  exclude-use-default: false
