
# YAML anchors for environment variables
x-api-env: &api-env
  NODE_ENV: ${NODE_ENV}
  API_PORT: ${API_PORT}
  API_STAGE: ${API_STAGE}
  API_PGHOST: ${API_PGHOST}
  API_PGUSER: ${API_PGUSER}
  API_PGPASSWORD: ${API_PGPASSWORD}
  API_PGDATABASE: ${API_PGDATABASE}
  API_PGPORT: ${API_PGPORT}
  API_DATABASE_URL: ${API_DATABASE_URL}
  API_JWT_SECRET: ${API_JWT_SECRET}

x-web-env: &web-env
  NODE_ENV: ${NODE_ENV}
  WEB_PORT: ${WEB_PORT}
  WEB_STAGE: ${WEB_STAGE}
  VITE_API_BASE_URL: ${VITE_API_BASE_URL}

x-db-backup-env: &db-backup-env
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  PGPASSWORD: ${POSTGRES_PASSWORD}
  BACKUP_INTERVAL_HOURS: ${BACKUP_INTERVAL_HOURS}

services:
  postgres:
    image: postgres:16
    container_name: spenicle-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile.dev
      args:
        <<: *api-env
    container_name: spenicle-api
    environment:
      <<: *api-env
      API_PGDATA: ${API_PGDATA}  # Additional env var not in build args
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./packages/api:/app/packages/api
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./.yarnrc.yml:/app/.yarnrc.yml
    depends_on:
      postgres:
        condition: service_healthy
    command: ["yarn", "workspace", "@spenicle/api", "dev"]
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: packages/web/Dockerfile.dev
      args:
        <<: *web-env
    container_name: spenicle-web
    environment:
      <<: *web-env
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - ./packages/web:/app/packages/web
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./.yarnrc.yml:/app/.yarnrc.yml
    depends_on:
      - api
    command: ["sh", "-c", "yarn workspace @spenicle/web dev --host 0.0.0.0 --port $$WEB_PORT"]
    restart: unless-stopped

volumes:
  postgres_data:
