name: Health Checks

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  health-checks:
    name: Validate Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Enable corepack
        run: corepack enable
        
      - name: Install dependencies
        run: yarn install
      
      - name: Type check
        run: yarn check
      
      - name: Lint
        run: yarn workspaces foreach -all --parallel --interlaced run lint
      
      - name: Run tests
        run: yarn workspaces foreach -all --parallel --interlaced run test
      
      - name: Build
        run: yarn workspaces foreach -all --parallel --interlaced run build
