export const DRAWER_ROUTES = {
  ACCOUNT_CREATE: "account-create",
  ACCOUNT_VIEW: "account-view",
  ACCOUNT_UPDATE: "account-update",
  CATEGORY_CREATE: "category-create",
  CATEGORY_VIEW: "category-view",
  CATEGORY_UPDATE: "category-update",
  TRANSACTION_CREATE: "transaction-create",
  TRANSACTION_VIEW: "transaction-view",
  TRANSACTION_UPDATE: "transaction-update",
  TRANSACTION_RECURRING_CREATE: "transaction-recurring-create",
  TRANSACTION_RECURRING_UPDATE: "transaction-recurring-update",
  TRANSACTION_INSTALLMENT_CREATE: "transaction-installment-create",
  TRANSACTION_INSTALLMENT_UPDATE: "transaction-installment-update",
  TRANSACTION_TEMPLATE_VIEW: "transaction-template-view",
  SELECT_SINGLE_ACCOUNT: "select-single-account",
  SELECT_SINGLE_CATEGORY: "select-single-category",
  INSIGHTS_FILTER: "insights-filter",
} as const;
